### PR TITLE
Revert "fixed some minor typos found during autumn datadive in the uk :)...

### PR DESCRIPTION
**Pull request by nickmcclellan**
..."

### CODE REVIEW

**Comment by andylolz** [comment]
lol sorry!

**Comment by andylolz** [comment]
I think we did the same thing :) Works now, anyway.

**Comment by ajschumacher** [comment]
what's the status of this pull request? @nickmcclellan? @andylolz? can we just close this?

**Comment by andylolz** [comment]
yep – this is closable. It’s a duplicate of #105.

**Comment by ajschumacher** [comment]
thanks @andylolz!

I AM AARON, CLOSER OF THE CLOSABLE

**Comment by andylolz** [comment]
:santa::santa::santa:

**Pull request closed without merging**
